name: perfhistory
description: VR project with Prof. Kumar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.1
  google_maps_flutter: ^2.1.3
  google_maps_flutter_web: ^0.3.2+1
  url_launcher: ^6.0.20
  cloud_firestore: ^2.2.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.2
  firebase_storage: ^10.0.1
  firebase_crashlytics: ^2.2.1
  firebase_remote_config: ^2.0.3
  firebase_dynamic_links: ^4.1.3
  mobile_scanner: ^1.0.0
  geolocator: ^8.2.0
  mapbox_gl: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
